version: 1.0.{build}
os: Visual Studio 2013

branches:
  only:
  - master

skip_tags: true

install:
- cmd: nuget restore src\NReco.LambdaParser.Portable.sln

build:
  project: src\NReco.LambdaParser.Portable.sln
  verbosity: minimal

test_script:
- cmd: nunit-console src\NReco.LambdaParser.Tests\bin\Debug\NReco.LambdaParser.Tests.dll